### PR TITLE
test: firebase pr preview

### PR DESCRIPTION
**Pull request by h16nning**

### CODE REVIEW

**Comment by eMerzh** [comment]
😲  🤯  soooo nice  ... hope you can make this work 🤞

**Comment by h16nning** [comment]
first issue was definitely that I only ran `npm run build` without a clean install before, so vite build was failing

**Comment by eMerzh** [comment]
i think you still need to "setup node" like in .github/workflows/check.yml

**Comment by h16nning** [comment]
I forgot to give read/write permissions to workflows. Then I noticed and thought I had changed the permissions but forgot to click save 🙄😂. But now that I modified the permissions again, it seems to work... 🎉

**Comment by eMerzh** [comment]
well done 👏  ... this is very nice :) it will help the reviews a lot

**Comment by h16nning** [comment]
it is weird that firebase pr preview doesn't work anymore

actually, I think it only worked for the first time...

**Comment by eMerzh** [comment]
> ?

yes i tried #121

**Comment by eMerzh** [comment]
seems ok now :) 
btw, wonder if you shouldn't put an expiration on PR previews or smth ? 
not sure how firebase "pricing" goes

**Comment by h16nning** [comment]
There is an automatic 7d expiration date on firebases end, I will see if that is enough.

**Comment by h16nning** [comment]
Bildschirmfoto 2024-03-12 um 23 40 45
It seems that it also automatically closes all previews after the pr is merged or closed.

I'm going with a free firebase plan right now, which has 10 GB hosting storage (using 37 MB as of now) and about 10 GB / month data transfer. Yesterday and today it accounts for more data transfer (at around 5,5 MB/d). This would mean 165 MB per mont.

So I don't worry too much about the limits 😅, the paid quotas would be ok for me too for these use cases.

I will have to see to if firebase would still be a good option for higher traffic... 🤔 It was to quickest to set-up for me but I thought about switching in the future maybe. Don't know yet

**Pull request closed without merging**
