### PR TITLE
feat: add edit modal

### PR DESCRIPTION
**Pull request by eMerzh**
Hey, 
small improvement, it seems to work well but not sure of the implications 🤔 

I just noticed the shortcut is now a bit more broken than before in notebookview,
but they probably need a rework anyway there 😅

### CODE REVIEW

**Comment by h16nning** [comment]
modifies a lot of lines, I am currently working on in the separate branch. We will need to see how we will merge those two PRs haha 😵‍💫

**Comment by eMerzh** [comment]
haha, don't worry, i can rebase this when the rest is merged... if the idea of this is ok for you

**Comment by eMerzh** [comment]
there you go, i rebased it :)

**Comment by h16nning** [comment]
thank you

**Pull request merged**
