### PR TITLE
Lint + Workflow

### PR DESCRIPTION
**Pull request by eMerzh**
Now that the formater is in place & there's a linter,
and typescript... maybe we can add a check to avoid things like #23 

we can use them informatively only if we like, but at least it will appear red before merging

**Note**:
For the sake of matching the project, i've disabled or lower to warning some issues; but maybe we might need to do a followup and progressively fix those :)

### CODE REVIEW

**Comment by h16nning** [comment]
I really have no experiences using GitHub workflows but it seems rational to have it 👍
I'll look into how it works 😌

**Comment by eMerzh** [comment]
you can do a few stuff from checks, to deploys, & stuff, also quite helpfull for letting you know early if something's wrong... 

if you think about something you want, or have questions, i might help :)

**Comment by h16nning** [comment]
Wow that sounds very useful!

So could I link a change to the main branch with creating a build and deploying it to firebase or other hosting?

**Comment by eMerzh** [comment]
Yes... i'm not THAT familiar with firebase, but yeah you definitely can do that https://firebase.google.com/docs/hosting/github-integration?hl=fr 

https://github.com/marketplace/actions/deploy-to-firebase-hosting

**Comment by h16nning** [comment]
Ok thanks I'll look at that

**Pull request merged**
